services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: apollonft_backend

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "4000"

    labels:
      - traefik.enable=true

      # Router
      - traefik.http.routers.apollonft-backend.rule=Host(`api.apollonft.io`)
      - traefik.http.routers.apollonft-backend.entrypoints=websecure
      - traefik.http.routers.apollonft-backend.tls=true
      - traefik.http.routers.apollonft-backend.tls.certresolver=letsencrypt

      # Service
      - traefik.http.services.apollonft-backend.loadbalancer.server.port=4000

      # Global middleware
      - traefik.http.routers.apollonft-backend.middlewares=default@file

    networks:
      - proxy

networks:
  proxy:
    external: true
